// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvknawrgveyymfgqtodz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2a25hd3JndmV5eW1mZ3F0b2R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDUyMDIsImV4cCI6MjA3MTAyMTIwMn0.UNE0F2Gr__tId1-A1kIrpkINVD7OpUDQDs1306I_dqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});